// Generated by CoffeeScript 1.6.2
(function() {
  $(document).ready(function() {
    var height, spacing;

    height = 50;
    spacing = 15;
    console.log("making request")
    return $.ajax({
      url: '/d3json.json',
      method: 'get',
      dataType: 'json',
      success: function(d3data) {
        var svg_element;

        svg_element = d3.select('div#d3container svg').selectAll('rect').data(d3data);
        return svg_element.enter().append('rect').attr('height', height).attr('width', 0).attr('y', function(value, i) {
          return i * (height + spacing) - spacing;
        }).transition().duration(1000).style('fill', 'yellow').attr('width', function(gitInfo) {
          return gitInfo.value * 10;
        });
      }
    });
  });

}).call(this);
